version: "3.9"  # optional since v1.27.0

services:
  company-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=company_db
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/